import java.util.Collection;
import java.util.Iterator;
import java.util.LinkedHashSet;
import java.util.Set;

/**
 * Wrapper for List of attributes with additional functionality
 */
public class Attributes extends LinkedHashSet<Attribute> {

	/**
	 * generated by eclipse 
	 */
	private static final long serialVersionUID = 3073117117232024505L;
	
	public boolean contains(String attrName) {
		for (Attribute a : this) {
			if (a.getName().equals(attrName)) return true;
		}
		return false;
	}
	
	public Attribute get(String attrName) {
		for (Attribute a : this) 
			if (a.getName().equals(attrName)) return a;
		// TODO: Is this the best way to handle the situation?
		throw new IllegalArgumentException("Does not contain " + attrName);
	}
	
}
